# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'QAndAApplication' do
pod 'ReactiveCocoa', '~> 2.0'
pod 'Firebase', '~> 2.2'
pod 'Mantle', '~> 2.0'
pod 'AFMInfoBanner'
end

target 'QAndAApplicationTests' do

end

